window.facultyJson = [
    {
      "name": "Ahrenes, Eric",
      "focus1": "Research",
      "focus2": null,
      "role": null,
      "modality": null,
      "degree": "PhD",
      "email": "eahrens@health.ucsd.edu",
      "title": "Professor",
      "team": null,
      "profileUrl": "http://profiles.ucsd.edu/eric.ahrens",
    },
    {
      "name": "Andre, Michael",
      "focus1": "Research",
      "focus2": null,
      "role": null,
      "modality": null,
      "degree": "PhD",
      "email": "mandre@health.ucsd.edu",
      "title": "Adjunct Professor",
      "team": null,
      "profileUrl": "http://profiles.ucsd.edu/michael.andre",
    },
    {
      "name": "Bae, Won",
      "focus1": "Research",
      "focus2": null,
      "role": null,
      "modality": null,
      "degree": "PhD",
      "email": "wbae@health.ucsd.edu",
      "title": "Associate Adjunct Professor",
      "team": null,
      "profileUrl": "http://profiles.ucsd.edu/won.bae",
    },
    {
      "name": "Berman, Zachary",
      "focus1": "Clinical",
      "focus2": null,
      "role": null,
      "modality": "Interventional Radiology",
      "degree": "MD",
      "email": "zberman@health.ucsd.edu",
      "title": "(HS) Associate Clinical Professor",
      "imageUrl": "https://res.cloudinary.com/dn78hfybw/image/upload/c_fill,ar_3:4,g_auto/v1744855642/Zach_Berman_u4dw2r.jpg",
      "profileUrl": "http://profiles.ucsd.edu/zachary.berman",
      "team": null,
    },
    {
      "name": "Bolar, Divya",
      "focus1": "Clinical",
      "focus2": null,
      "role": null,
      "modality": "Musculoskeletal Imaging",
      "degree": "MD",
      "email": "dbolar@health.ucsd.edu",
      "title": "Assistant Professor / In Residence",
      "profileUrl": "https://profiles.ucsd.edu/divya.bolar",
      "team": null,
    },
    {
      "name": "Bykowski, Julie",
      "focus1": "Clinical",
      "focus2": null,
      "role": "Division Chief",
      "modality": "Neuroimaging",
      "degree": "MD",
      "email": "jbykowski@health.ucsd.edu",
      "title": "(HS) Clinical Professor",
      "imageUrl": "https://res.cloudinary.com/dn78hfybw/image/upload/c_fill,ar_3:4,g_auto/v1744855650/Julie_Bykowski_dle5ik.jpg",
      "profileUrl": "http://profiles.ucsd.edu/julie.marekbykowski",
      "team": 3,
    },
    {
      "name": "Brouha, Sharon",
      "focus1": "Clinical",
      "focus2": null,
      "role": null,
      "modality": "Cardiothoracic Imaging",
      "degree": "MD, MPH",
      "email": "sbrouha@health.ucsd.edu",
      "title": "(HS) Clinical Professor",
      "profileUrl": "http://profiles.ucsd.edu/sharon.brouha",
      "team": null,
    },
    {
      "name": "Chang, Eric",
      "focus1": "Research",
      "focus2": null,
      "role": "Associate Director, T32 Residency ",
      "modality": "Musculoskeletal Imaging",
      "degree": "MD",
      "email": "e8chang@health.ucsd.edu",
      "title": "Adjunct Professor",
      "profileUrl": "http://profiles.ucsd.edu/eric.chang",
      "team": null,
    },
    {
      "name": "Chang, Jennifer",
      "focus1": "Clinical",
      "focus2": null,
      "role": "Director, MRI Fellowship Program",
      "modality": "Neuroimaging",
      "degree": "MD",
      "email": "jenchang@health.ucsd.edu",
      "title": "(HS) Associate Clinical Professor",
      "imageUrl": "https://res.cloudinary.com/dn78hfybw/image/upload/c_fill,ar_3:4,g_auto/v1744855645/Jen_Chang_z2kczb.jpg",
      "profileUrl": "http://profiles.ucsd.edu/jennifer.chang",
      "team": 4,
    },
    {
      "name": "Chapelin, Fanny",
      "focus1": "Research",
      "focus2": null,
      "role": "Associate Director, T32 Residency ",
      "modality": null,
      "degree": "PhD",
      "email": "fachapelin@health.ucsd.edu",
      "title": "Assistant Professor",
      "profileUrl": "https://profiles.ucsd.edu/fanny.chapelin",
      "team": null,
    },
    {
      "name": "Chen, James",
      "focus1": "Clinical",
      "focus2": null,
      "role": "Director, Neuro Fellowship Program",
      "modality": "Neuroimaging",
      "degree": "MD",
      "email": "Jyc042@health.ucsd.edu",
      "title": null,
      "profileUrl": "https://profiles.ucsd.edu/james.chen",
      "team": 4,
    },
    {
      "name": "Chen, Chi-Hua",
      "focus1": "Research",
      "focus2": null,
      "role": null,
      "modality": null,
      "degree": "PhD",
      "email": "chc101@health.ucsd.edu",
      "title": "Adjunct Professor",
      "profileUrl": "http://profiles.ucsd.edu/chi-hua.chen",
      "team": null,
    },
    {
      "name": "Cheng, Karen",
      "focus1": "Clinical",
      "focus2": null,
      "role": null,
      "modality": "Musculoskeletal Imaging",
      "degree": "MD",
      "email": "kcheng@health.ucsd.edu",
      "title": "Assistant Professor of Clinical",
      "imageUrl": "https://res.cloudinary.com/dn78hfybw/image/upload/c_fill,ar_3:4,g_auto/v1744855644/Karen_Cheng_cicudp.jpg",
      "profileUrl": "http://profiles.ucsd.edu/karen.chen",
      "team": null,
    },
    {
      "name": "Chung, Christine",
      "focus1": "Clinical",
      "focus2": "Research",
      "role": "Department Chair",
      "modality": "Musculoskeletal Imaging",
      "degree": "MD",
      "email": "cbchung@health.ucsd.edu",
      "title": "Professor / In Residence",
      "imageUrl": "https://res.cloudinary.com/dn78hfybw/image/upload/c_fill,ar_3:4,g_auto/v1744855646/Chung_Christine_tlj4s5.jpg",
      "profileUrl": "http://profiles.ucsd.edu/christine.chung",
      "team": 1,
    },
    {
      "name": "Dale, Anders",
      "focus1": "Research",
      "focus2": null,
      "role": null,
      "modality": null,
      "degree": "PhD",
      "email": "amdale@health.ucsd.edu",
      "title": "Professor",
      "profileUrl": "http://profiles.ucsd.edu/anders.dale",
      "team": null,
    },
    {
      "name": "Dorros, Stephen",
      "focus1": "Clinical",
      "focus2": null,
      "role": "Vice Chair of Business Development",
      "modality": "Musculoskeletal Imaging",
      "degree": "MD",
      "email": "sdorros@health.ucsd.edu",
      "title": "(HS) Clinical Professor",
      "profileUrl": "http://profiles.ucsd.edu/stephen.dorros",
      "team": 2,
    },
    {
      "name": "Du, Jiang",
      "focus1": "Research",
      "focus2": null,
      "role": null,
      "modality": null,
      "degree": "PhD",
      "email": "jiangdu@health.ucsd.edu",
      "title": "Professor / In Residence",
      "profileUrl": "http://profiles.ucsd.edu/jiang.du",
      "team": null,
    },
    {
      "name": "El Kaffas, Ahmed",
      "focus1": "Research",
      "focus2": null,
      "role": null,
      "modality": null,
      "degree": "PhD",
      "email": "aelkaffas@health.ucsd.edu",
      "title": "Associate Professor/In Residence",
      "profileUrl": "https://profiles.ucsd.edu/admed.elkaffas",
      "team": null,
    },
    {
      "name": "Elmi, Azadeh",
      "role": null,
      "modality": "Breast Imaging",
      "degree": "MD",
      "email": "aelmi@health.ucsd.edu",
      "title": "(HS) Associate Clinical Professor",
      "imageUrl": "https://res.cloudinary.com/dn78hfybw/image/upload/c_fill,ar_3:4,g_auto/v1744855647/Azadeh_Elmi_izwizx.jpg",
      "team": null,
    },
    {
      "name": "Farid, Nikdokht",
      "focus1": "Clinical",
      "focus2": null,
      "role": null,
      "modality": "Neuroimaging",
      "degree": "MD",
      "email": "nfarid@health.ucsd.edu",
      "title": "(HS) Clinical Professor",
      "imageUrl": "https://res.cloudinary.com/dn78hfybw/image/upload/c_fill,ar_3:4,g_auto/v1744855643/Niky_Farid_rikonv.jpg",
      "profileUrl": "http://profiles.ucsd.edu/nikdokht.farid",
      "team": null,
    },
    {
      "name": "Fazeli, Soudabeh",
      "focus1": "Clinical",
      "focus2": null,
      "role": "Director, Breast Imaging Fellowship Program",
      "modality": "Breast Imaging",
      "degree": "MD",
      "email": "sfazelidehkordy@health.ucsd.edu",
      "title": "(HS) Assistant Clinical Professor",
      "imageUrl": "https://res.cloudinary.com/dn78hfybw/image/upload/c_fill,ar_3:4,g_auto/v1744855643/Soudah_Fazeli_q1h1cr.jpg",
      "team": 4,
    },
    {
      "name": "Fliszar, Evelyne",
      "focus1": "Clinical",
      "focus2": null,
      "role": null,
      "modality": "Musculoskeletal Imaging",
      "degree": "MD",
      "email": "efliszar@health.ucsd.edu",
      "title": "(HS) Clinical Professor",
      "imageUrl": "https://res.cloudinary.com/dn78hfybw/image/upload/c_fill,ar_3:4,g_auto/v1744855646/Evelyne_Fliszar_nu1erv.jpg",
      "profileUrl": "http://profiles.ucsd.edu/evelyne.fliszar",
      "team": null,
    },
    {
      "name": "Frank, Lawrence",
      "focus1": "Research",
      "focus2": null,
      "role": null,
      "modality": null,
      "degree": "PhD",
      "email": "lrfrank@health.ucsd.edu",
      "title": "Professor",
      "profileUrl": "http://profiles.ucsd.edu/lawrence.frank",
      "team": null,
    },
    {
      "name": "Gamie, Sherief",
      "focus1": "Clinical",
      "focus2": null,
      "role": "Division Chief",
      "modality": "Nuclear Medicine",
      "degree": "MD, PhD",
      "email": "sgamie@health.ucsd.edu",
      "title": "(HS) Clinical Professor",
      "profileUrl": "http://profiles.ucsd.edu/sherief.gamie",
      "team": 3,
    },
    {
      "name": "Gentili, Amilcare",
      "focus1": "Clinical",
      "focus2": null,
      "role": null,
      "modality": "Musculoskeletal Imaging",
      "degree": "MD",
      "email": "agentili@health.ucsd.edu",
      "title": "Professor of Clinical",
      "profileUrl": "http://profiles.ucsd.edu/amilcare.gentili",
      "team": null,
    },
    {
      "name": "Gordon, Emile",
      "focus1": "Clinical",
      "focus2": null,
      "role": null,
      "modality": "Cardiothoracic Imaging",
      "degree": "MD",
      "email": "emgordon@health.ucsd.edu",
      "title": "Assistant Professor of Clinical",
      "profileUrl": "http://profiles.ucsd.edu/emile.gordon",
      "team": null,
    },
    {
      "name": "Hahn, Michael",
      "focus1": "Clinical",
      "focus2": null,
      "role": "Director, Body Imaging Fellowship Program",
      "modality": "Body Imaging",
      "degree": "MD, PhD",
      "email": "mehahn@health.ucsd.edu",
      "title": "Associate Professor of Clinical",
      "profileUrl": "http://profiles.ucsd.edu/michael.hahn",
      "team": 4,
    },
    {
      "name": "Halgren, Eric",
      "focus1": "Research",
      "focus2": null,
      "role": null,
      "modality": null,
      "degree": "PhD",
      "email": "ehalgren@health.ucsd.edu",
      "title": "Professor",
      "profileUrl": "http://profiles.ucsd.edu/eric.halgren",
      "team": null,
    },
    {
      "name": "Hall, David",
      "focus1": "Research",
      "focus2": null,
      "role": null,
      "modality": null,
      "degree": "PhD",
      "email": "djhall@health.ucsd.edu",
      "title": "Adjunct Professor",
      "profileUrl": "http://profiles.ucsd.edu/david.hall",
      "team": null,
    },
    {
      "name": "Handwerker, Jason",
      "focus1": "Clinical",
      "focus2": null,
      "role": "Vice Chair of Quality & Safety",
      "modality": "Neuroimaging",
      "degree": "MD",
      "email": "jhandwerker@health.ucsd.edu",
      "title": "(HS) Clinical Professor",
      "imageUrl": "https://res.cloudinary.com/dn78hfybw/image/upload/c_fill,ar_3:4,g_auto/v1744855645/Jason_Handwerker_vulmrs.jpg",
      "profileUrl": "http://profiles.ucsd.edu/jason.handwerker",
      "team": 2,
    },
    {
      "name": "Hawley, Daniel",
      "focus1": "Clinical",
      "focus2": null,
      "role": "MRI Modality Chief",
      "modality": "Neuroimaging",
      "degree": "MD",
      "email": "dhawley@health.ucsd.edu",
      "title": "(HS) Clinical Professor",
      "profileUrl": "http://profiles.ucsd.edu/daniel.hawley",
      "team": 4,
    },
    {
      "name": "Hero Chung, Jonathan",
      "focus1": "Clinical",
      "focus2": null,
      "role": "Division Chief",
      "modality": "Cardiothoracic Imaging",
      "degree": "MD",
      "email": "jherochung@health.ucsd.edu",
      "title": "Professor of Clinical",
      "profileUrl": "http://profiles.ucsd.edu/jonathan.herochung",
      "team": 3,
    },
    {
      "name": "Horowitz, Michael",
      "focus1": "Clinical",
      "focus2": null,
      "role": "Director, Cardiothoracic Imaging Fellowship Program",
      "modality": "Cardiothoracic Imaging",
      "degree": "MD, PhD",
      "email": "mjhorowitz@health.ucsd.edu",
      "title": "(HS) Associate Clinical Professor",
      "imageUrl": "https://res.cloudinary.com/dn78hfybw/image/upload/c_fill,ar_3:4,g_auto/v1744855644/Michael_Horowitz_ow5iga.jpg",
      "profileUrl": "https://profiles.ucsd.edu/michael.horowitz",
      "team": 4,
    },
    {
      "name": "Hsiao, Albert",
      "focus1": "Clinical",
      "focus2": null,
      "role": null,
      "modality": "Cardiothoracic Imaging",
      "degree": "MD, PhD",
      "email": "a3hsiao@health.ucsd.edu",
      "title": "Professor In Residence",
      "imageUrl": "https://res.cloudinary.com/dn78hfybw/image/upload/c_fill,ar_3:4,g_auto/v1744855648/Albert_Hsiao_tpg3te.jpg",
      "profileUrl": "http://profiles.ucsd.edu/albert.hsiao",
      "team": null,
    },
    {
      "name": "Huang, Brady",
      "focus1": "Clinical",
      "focus2": null,
      "role": "Division Chief",
      "modality": "Musculoskeletal Imaging",
      "degree": "MD",
      "email": "b4huang@health.ucsd.edu",
      "title": "(HS) Clinical Professor",
      "imageUrl": "https://res.cloudinary.com/dn78hfybw/image/upload/c_fill,ar_3:4,g_auto/v1744855647/Brady_Huang_zbfpre.jpg",
      "profileUrl": "http://profiles.ucsd.edu/brady.huang",
      "team": 3,
    },
    {
      "name": "Huang, Mingxiong",
      "focus1": "Research",
      "focus2": null,
      "role": null,
      "modality": null,
      "degree": "PhD",
      "email": "mxhuang@health.ucsd.edu",
      "title": "Adjunct Professor",
      "profileUrl": "http://profiles.ucsd.edu/mingxiong.huang",
      "team": null,
    },
    {
      "name": "Ingraham, Christopher",
      "focus1": "Clinical",
      "focus2": null,
      "role": null,
      "modality": "Interventional Radiology",
      "degree": "MD",
      "email": "cingraham@health.ucsd.edu",
      "title": "(HS) Associate Clinical Professor",
      "profileUrl": "http://profiles.ucsd.edu/christopher.ingraham",
      "team": null,
    },
    {
      "name": "Jaffray, Paul",
      "focus1": "Clinical",
      "focus2": null,
      "role": "Modality Chief",
      "modality": "Emergency Radiology",
      "degree": "MD",
      "email": "pjaffray@health.ucsd.edu",
      "title": "(HS) Associate Clinical Professor",
      "profileUrl": "http://profiles.ucsd.edu/paul.jaffray",
      "team": 4,
    },
    {
      "name": "Jerban, Saeed",
      "focus1": "Research",
      "focus2": null,
      "role": null,
      "modality": null,
      "degree": "PhD",
      "email": "sjerban@health.ucsd.edu",
      "title": "Assistant Adjunct Professor",
      "profileUrl": "http://profiles.ucsd.edu/saeed.jerban",
      "team": null,
    },
    {
      "name": "Jernigan, Terry",
      "focus1": "Research",
      "focus2": null,
      "role": null,
      "modality": null,
      "degree": "PhD",
      "email": "tjernigan@health.ucsd.edu",
      "title": "Professor",
      "profileUrl": "http://www.cogsci.ucsd.edu/~jernigan/",
      "team": null,
    },
    {
      "name": "Khurana, Aman",
      "focus1": "Clinical",
      "focus2": null,
      "role": null,
      "modality": "Body Imaging",
      "degree": "MD, MBBS",
      "email": "a1khurana@health.ucsd.edu",
      "title": "Associate Professor of Clinical",
      "profileUrl": "http://profiles.ucsd.edu/aman.khurana",
      "team": null,
    },
    {
      "name": "Liau, Joy",
      "focus1": "Clinical",
      "focus2": null,
      "role": null,
      "modality": "Body Imaging",
      "degree": "MD, PhD",
      "email": "jliau@health.ucsd.edu",
      "title": "(HS) Associate Clinical Professor",
      "profileUrl": "https://profiles.ucsd.edu/joy.liau",
      "team": null,
    },
    {
      "name": "Lim, Vivian",
      "focus1": "Clinical",
      "focus2": null,
      "role": null,
      "modality": "Body Imaging",
      "degree": "MD",
      "email": "vlim@health.ucsd.edu",
      "title": "Assistant Professor of Clinical",
      "profileUrl": "http://profiles.ucsd.edu/vivian.lim",
      "imageUrl": "https://res.cloudinary.com/dn78hfybw/image/upload/c_fill,ar_3:4,g_auto/v1744855642/Vivian_Lim_ojeqk3.jpg",
      "team": null,
    },
    {
      "name": "Liu, Thomas",
      "focus1": "Research",
      "focus2": null,
      "role": "Vice Chair of Research",
      "modality": null,
      "degree": "PhD, MBA",
      "email": "ttliu@health.ucsd.edu",
      "title": "Professor",
      "profileUrl": "http://profiles.ucsd.edu/thomastao-ming.liu",
      "team": 2,
    },
    {
      "name": "Loehfelm, Thomas",
      "focus1": "Clinical",
      "focus2": null,
      "role": null,
      "modality": "Body Imaging",
      "degree": "MD, PhD",
      "email": "tloehfelm@health.ucsd.edu",
      "title": "Associate Professor of Clinical",
      "profileUrl": "http://profiles.ucsd.edu/thomas.loehfelm",
      "team": null,
    },
    {
      "name": "Ma, Yajun",
      "focus1": "Research",
      "focus2": null,
      "role": null,
      "modality": null,
      "degree": "PhD",
      "email": "yam013@health.ucsd.edu",
      "title": "Associate Adjunct Professor",
      "profileUrl": "http://profiles.ucsd.edu/yajun.ma",
      "team": null,
    },
    {
      "name": "Marek Bykowski, Julie",
      "focus1": "Clinical",
      "focus2": null,
      "role": "Division Chief",
      "modality": "Neuroimaging",
      "degree": "MD",
      "email": "jbykowski@health.ucsd.edu",
      "title": "Professor of Clinical",
      "profileUrl": "http://profiles.ucsd.edu/julie.marekbykowski",
      "team": 3,
    },
    {
      "name": "Marks, Robert",
      "focus1": "Clinical",
      "focus2": null,
      "role": "Division Chief",
      "modality": "Body Imaging",
      "degree": "MD",
      "email": "rmarks@health.ucsd.edu",
      "title": "(HS) Clinical Professor",
      "profileUrl": "http://profiles.ucsd.edu/robert.marks",
      "team": 3,
    },
    {
      "name": "Mcnamee, Cairine",
      "focus1": "Clinical",
      "focus2": null,
      "role": null,
      "modality": "Body Imaging",
      "degree": "MD",
      "email": "cmcnamee@health.ucsd.edu",
      "title": "(HS) Assistant Clinical Professor",
      "profileUrl": "http://profiles.ucsd.edu/cairine.mcnamee",
      "team": null,
    },
    {
      "name": "Mcveigh, Elliot",
      "focus1": "Research",
      "focus2": null,
      "role": null,
      "modality": null,
      "degree": "PhD",
      "email": "emcveigh@health.ucsd.edu",
      "title": "Professor",
      "profileUrl": "http://profiles.ucsd.edu/elliot.mcveigh",
      "team": null,
    },
    {
      "name": "Meisinger, Quinn",
      "focus1": "Clinical",
      "focus2": null,
      "role": "Program Director, IRDR Residency Program",
      "modality": "Interventional Radiology",
      "degree": "MD",
      "email": "qmeisinger@health.ucsd.edu",
      "title": null,
      "profileUrl": "http://profiles.ucsd.edu/quinn.meisinger",
      "team": 4,
    },
    {
      "name": "Minocha, Jeet",
      "focus1": "Clinical",
      "focus2": null,
      "role": "Division Chief",
      "modality": "Interventional Radiology",
      "degree": "MD",
      "email": "jminocha@health.ucsd.edu",
      "title": "Professor of Clinical",
      "profileUrl": "http://profiles.ucsd.edu/jeet.minocha",
      "team": 3,
    },
    {
      "name": "Miyazaki, Mitsue",
      "focus1": "Research",
      "focus2": null,
      "role": null,
      "modality": null,
      "degree": "PhD",
      "email": "mimiyazaki@health.ucsd.edu",
      "title": "Adjunct Professor",
      "profileUrl": "http://profiles.ucsd.edu/mitsue.miyazaki",
      "team": null,
    },
    {
      "name": "Murphy, Paul",
      "focus1": "Clinical",
      "focus2": null,
      "role": "Vice Chair of Information Technology",
      "modality": "Body Imaging",
      "degree": "MD, PhD",
      "email": "pmmurphy@health.ucsd.edu",
      "title": "(HS) Associate Clinical Professor",
      "imageUrl": "https://res.cloudinary.com/dn78hfybw/image/upload/c_fill,ar_3:4,g_auto/v1744855643/Paul_Murphy_a2jpgd.jpg",
      "profileUrl": "http://profiles.ucsd.edu/paul.murphy",
      "team": 2,
    },
    {
      "name": "Newton, Isabel",
      "focus1": "Clinical",
      "focus2": "Research",
      "role": null,
      "modality": "Interventional Radiology",
      "degree": "MD, PhD",
      "email": "inewton@health.ucsd.edu",
      "title": "(HS) Clinical Professor",
      "imageUrl": "https://res.cloudinary.com/dn78hfybw/image/upload/c_fill,ar_3:4,g_auto/v1744855645/Isabel_Newton_mxaegd.jpg",
      "profileUrl": "http://profiles.ucsd.edu/isabel.newton",
      "team": null,
    },
    {
      "name": "Ojeda-Fournier, Haydee",
      "focus1": "Clinical",
      "focus2": null,
      "role": "Division Chief",
      "modality": "Breast Imaging",
      "degree": "MD",
      "email": "hojeda@health.ucsd.edu",
      "title": "(HS) Clinical Professor",
      "profileUrl": "http://profiles.ucsd.edu/haydee.ojeda-fournier",
      "team": 3,
    },
    {
      "name": "Parikh, Rupal",
      "focus1": "Clinical",
      "focus2": null,
      "role": null,
      "modality": "Interventional Radiology",
      "degree": "MD",
      "email": "ruparikh@health.ucsd.edu",
      "title": "(HS) Assistant Clinical Professor",
      "imageUrl": "https://res.cloudinary.com/dn78hfybw/image/upload/c_fill,ar_3:4,g_auto/v1744855643/Rupal_Parikh_drjhas.jpg",
      "profileUrl": "http://profiles.ucsd.edu/rupal.parikh",
      "team": null,
    },
    {
      "name": "Pathria, Mini",
      "focus1": "Clinical",
      "focus2": null,
      "role": null,
      "modality": "Musculoskeletal Imaging",
      "degree": "MD",
      "email": "mpathria@health.ucsd.edu",
      "title": "Professor of Clinical",
      "imageUrl": "https://res.cloudinary.com/dn78hfybw/image/upload/c_fill,ar_3:4,g_auto/v1744855644/Mini_Pathria_abqz1y.jpg",
      "profileUrl": "http://profiles.ucsd.edu/mini.pathria",
      "team": null,
    },
    {
      "name": "Pohlen, Michael",
      "focus1": "Clinical",
      "focus2": null,
      "role": null,
      "modality": "Cardiothoracic Imaging",
      "degree": "MD",
      "email": "mpohlen@health.ucsd.edu",
      "title": "Assistant Professor of Clinical",
      "imageUrl": "https://res.cloudinary.com/dn78hfybw/image/upload/c_fill,ar_3:4,g_auto/v1744855644/Michael_Pohlen_wjnmzp.jpg",
      "profileUrl": "http://profiles.ucsd.edu/michael.pohlen",
      "team": null,
    },
  ];
